sudo: false
language: python
services:
- docker
python:
- '3.8'
script:
- docker build .
deploy:
  provider: pypi
  user: __token__
  password:
    secure: Of328K+Whm/K8JG4PuX1oKyIdtES/q4wYyrmsdAX0d3wYYyEVpPN/bdB5gYrvAH4B9XUgDYkb3OyXb4pd4rJfH1lsbzHKQemikjqEuVkX/JPef/FUkWm7AsHPrKBPVslkk1ldugwlAt042EqrotGaarFb+Kqbr2691pQXoGciLeMDmJh3/UQbh/QTIDZBrsd1+SKs0eXqPU/0NbQTmHXZGC/YrrdYm/20n0YXlJN8nLxQ2GPH9JvHEtZQPIl8MRsz3e/g2WsABVaGsPFDt7a77L9MxDx+PBxlwR2CaTaqORWpBRm/7bComWez3R2g93hcobMcBSOURLBgffIg+3nV8OHG+fXwBqqV/vA/Q847JppdorKGFj0Db+93vRRYAIC8euiEyIYFYcVMDRQsmkUmStVKjZcRieMWi0aq+T/8tMtZcViJnup915cQYBsjYvYhsEtQq4JsHCzjKkPVfZT1y4CXTHyYeJN5+dWq3Syqv4pKmTrwrlg+cyV46jsDCqznVvMzORBLrJr3FpgJpDDke3tdnGTMY1Eo+cKEHJxOKWHtPKT4jgGYT05BdY7e9JfM53F6SqoooDbcxTQGgzBpiruAUFp8rEGUHglTy2tk6hJ82PkpgGI//MgrKSUNZTsVASsrei8qah3OcvweC0RynUM2ppxSSO/mbSx4iJXsBg=
  on:
    tags: true
