sudo: false
language: python
services:
- docker
python:
- '3.8'
script:
- docker build .
deploy:
  provider: pypi
  user: __token__
  password:
    secure: mQDAyHqZXUTqxUIuJ4toD593fM+OZE5Nf5qjMmlZgzt78ZQa0q3nzt1AubPi/qeMdg5BVEEwVaLjkCbiaRFJEfyxwqoZ+FASjboMMM1YC8VjSPFYtmfQbNzsjoxxWrPMQno3KxkkVnoLFEHtpiPw1L7Cgc218JdSwQY1MTSGQTllF1zLPmfyBPsC9ARNN770ZE/OwOa5chEELzF4+B+cKuZBeVFNYOQKeSVPZnDu5A1/ZsWdt4eQzas5CIfLoq7zYM6WB6KSCrQFCBhlIHjBprrYVYL0TVVuFW9Kj6n2hfu10a9H+y7P5Ta6hfump6kCL07zLmmpH5qrjx5FYJyGLbAmLN6otj/wGk90eTmDVFVYHVjepCxI2j0DUJtQh/2OIAlOs/fkyW6BMKIaxIKztS/U1cy6yNyUMfpn2ZbUgZB5ZSMxOFKGTczwYrGUwkls8mAmQ5GwOrXmWsRg1jZJ7yUcIceX8L38+xmP1uK/UD9N0884qoxuIxdUHrEdXAWojP3te3qo+3DxZ7D0WxLpnuhX4gotaK3PTfXPAplcYitVel7jPWzJO2jslgu66R3Trw+U1F5jqznLeRtWuAR+Px+wF7sxhygBO6o18LksSUurAKvy2E0F0rptYt2UfKrycQQ7cY4Tf8cCH+kZGyppcJg+TjmeCkzb5G6QpANxwaE=
  on:
    tags: true
