os: linux
dist: xenial
language: python
services:
- docker
python:
- '3.8'
script:
- docker build .
deploy:
  provider: pypi
  username: __token__
  password:
    secure: VKFnC8aFFeNkFAOeg8b43BlEGFN66KZz6JU29tZIyxkO/hbzEFWuWpbhBMbfU4DnwESanNdxA7oImHsIv72cuW8rSYzCK6GK22tV1i7YFsGLnutRm09vbK7x9R6JAL6XBIZudH+FGZ3jCsvLRrh9fnT72V5dQ564ZevqKAfs/k1WS0F8OmgwrsAzAbt4eV+xDa0rBE79NmNpudBtlgX9zns42WYxJVPcu9Snvkotkh3BLFzhXKpckWWIeJnU2qxzznP3wOLFh4o2rfVQ/ZE+Qia7IYnqRYK/kfrJYd5CN5j2NBfTl+BN/RP2ODKG+FFMImSQDpkgBISgax2u8sEVELnPK6HHwC5ceN94zEz1unY1YS0IOOAZp4TLCus6mg4EM9zc/aU4qSqVDU6LIN5YzghhLwHJlOM0006x+ndWyHcHiUr3AKWBXT55jEWlNsvoE5PG+RGO1NV4jRcjpMhiTwx3Xg0G51OwSEkQyPyuzKBqO0YXKndix4q/yjXyQkfenXLUhjAeZoaSn4y++89HXyNVOhPDXXAqe5bAvp1mh4wFvdf1peMKFf+Z18wf3szqqyxpWEZzhSrqic2u8fBjZf3o9CulK9Tn2gXHQSOM+Hj6AbGDGQxNJVTgH3i5lo8fyid25wZShqVK7UFYnRt7xfnkTd9tJnBxVxW3DycQRlI=
  on:
    tags: true
