os: linux
dist: xenial
language: python
services:
- docker
python:
- '3.8'
script:
- docker build .
deploy:
  provider: pypi
  username: __token__
  password:
    secure: maWaGzmWUzQ19nQoe+PLLq8qaJL6PWkRf1MI1w8MjbsVf+O2TBdgwhzcUnM2dkLVMnTmaxxa4IfTF81B/bcJRUbl841ep7rvjEhjdWDN317sZJbGtNwMgM6PksEEKaPCdOMki41NmYlrD+Ny/ZcLDMt0tzCGd0t+pJlU20319EulRbeSogJla5v/OpiG8+gfORlVBKTHo5e7aYGB0kNvKtNPtWeVhJuWkrLyKQq7X9qmaFS2mpY1FcurC8fNUx2SQpfako76rEeR1aCMfD3kjV2eJ2ZLM4bKtAGhvNirKcLDVbdg4sMycVNnHmz40W7UOmpb/MufHMMXN4pOryFJDB7jEaTyQsKSDOZVH63+mfO9w/jcsN+qn0eywKjWQ+mQSjT0oPBUFhQzCdZyLkMz+cD7J9krxSInbiUN+/JBPlBxzViJN8P7PHMRALki07k/txmtuMaP400L7WQgHp1/u1w30Y7xmnSG6Yi+ZqE62cESyXbUkjP2FCUc5R830ahM2VCRt4GQoZ8CyF2xE0tKLfuwko8V/fNZqzqvpAc6WKxTst/VtRzFFUWJlWhD0A9rTRsd7Fy4m4bnZ/YpOTgqoxdMstt3lDAqtiFSheITJYMImrk+u1gMhWJ8LvupcUHVusQEDzzTMxdzmjgojhVBpGBUZ7pujLHn+6y+3V9p37A=
  on:
    tags: true
